# Generated by Django 5.2.12 on 2026-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_alter_bookmodel_book_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('date_of_birth', models.DateField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(related_name='books', to='books.bookmodel')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'AuthorModel',
                'ordering': ['pub_date'],
            },
        ),
    ]
