# Generated by Django 5.2.12 on 2026-03-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0004_bookmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.bookmodel'),
        ),
    ]
