# Generated by Django 5.2.12 on 2026-03-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_authormodel_books'),
        ('books', '0005_remove_bookmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='authors', to='books.bookmodel'),
        ),
    ]
