# Generated by Django 5.2.12 on 2026-04-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_authormodel_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
