# Generated by Django 5.2.12 on 2026-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('date', models.DateField()),
                ('book_file', models.FileField(upload_to='media')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'BookModel',
                'ordering': ['pub_date'],
            },
        ),
    ]
