# Generated by Django 5.2.12 on 2026-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookmodel_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_file',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
