# Generated by Django 5.2.12 on 2026-03-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0003_alter_bookmodel_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='author',
            field=models.ManyToManyField(related_name='authors', to='authors.authormodel'),
        ),
    ]
