# Generated by Django 5.2.12 on 2026-03-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='author',
        ),
    ]
