# Generated by Django 5.2.12 on 2026-04-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_bookmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
